"""删除用户地址

Revision ID: 91df77c89303
Revises: c84fae3e5daa
Create Date: 2021-11-06 18:07:59.827881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91df77c89303'
down_revision = 'c84fae3e5daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
